spring.application.name=LeetScan

server.port=8082

# Gemini
GEMINI_API_KEY=${GEMINI_API_KEY}

# GitHub
github.token=${GITHUB_TOKEN}

# Database
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true